### ISSUE TITLE
Organisation of Achievement Page

### ISSUE THREAD

**Issue by AthiraLekshmiCV** [amfoss/club-website-2017#14]
In contributions under achievements page, the piechart shown lists only contributions to Wikimedia foundation. The actual piechart in listed only when we click on 'View all contributions.

The contributions will be better listed if organised according to organisations.

**Comment by a0xnirudh** [comment]
Already reported. #13 . Modified bug report #16

**Comment by ash1794** [comment]
Confirm if this commit https://github.com/amfoss/website/commit/527f7c45cd6ca4e6036d6fe920c3fdc7e0ba33da fixes this isssue? I have no way to verify.
