### ISSUE TITLE
Public display of debug information

### ISSUE THREAD

**Issue by a0xnirudh** [amfoss/club-website-2017#2]
Because the **DEBUG = true** flag is now set, the site is displaying debug informations to public if we try to access an invalid page. This should be fixed ASAP.

eg: http://foss.amrita.ac.in/s404

**Comment by tonythomas01** [comment]
fixed manually! almost broke the site though :\
file changed : fossWebsite/local_settings.py

Would we want a custom 404 page ? Can you request that as an enhancement ?

**Comment by a0xnirudh** [comment]
yes, as off now we have a simple apache 404 not found error page. It would be nice to have a good looking 404 page.

**Comment by ash1794** [comment]
This doesn't seem to be fixed. Needs to be fixed ASAP.

**Comment by tonythomas01** [comment]
Fixed in production
