### ISSUE TITLE
Writing Style in the website

### ISSUE THREAD

**Issue by tssurya** [amfoss/club-website-2017#21]
I have noticed that the style of writing the various descriptions in the website is informal with short forms that should be used only  colloquially. Example We're and We'd etc.. Kindly avoid this and use We are and We would.

**Comment by tonythomas01** [comment]
Can you point out where exactly that happens ? Like is it in the homepage ? if so - you would'be able to see it somewhere in https://github.com/amfoss/website/blob/master/templates/home.html

**Comment by tssurya** [comment]
Sorry for not mentioning that. It is in the home page at lines 90 and 99 in the code for the home page in the above mentioned link.

**Comment by tonythomas01** [comment]
Can you submit a patch for that one ?

Thanks,
Tony Thomas http://tttwrites.wordpress.com/
FOSS@Amrita http://foss.amrita.ac.in

_"where there is a wifi, there is a way"_

On Sun, Feb 22, 2015 at 6:28 PM, Surya Seetharaman <notifications@github.com

**Comment by tonythomas01** [comment]
Hi,

I&#39;d like to add you to my professional network on LinkedIn.
- Tony

Accept: https://www.linkedin.com/blink?simpleRedirect=3cUe3ATd3gTcjANejcNdPkTejkZh4BKrSBQonhFtCVF9AhgdCBjcAx4fnBBiShBsC5EsOpQsSlRpRZBt6BSrCAZqSkConhzbmlQqnpKqiRQsSlRpORIrmkZpSVFqSdxsDgCpnhFtCV9pSlipn9Mfm4CszkJrmlDom5FdCAJcnoVoSBJbjRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I5975714342895652864_500&markAsRead=

You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/blink?simpleRedirect=78RbmRBpS5xqjpFbj5SemdFriQZp6BB9DF1r4pzoSYRsAd3gQBEumAPsmAMu6UUrnwTjmhCpBAUm3tdp3hWqmNDoQ9zl78TunkPt3h4r39ienlpoORojCVll493rz12rkJls5cPr65igmZNj5dik6dbekpkt3gUhPx6gAp3nP9ahCBIp3lNm7tip59ghkp2rQAOhQ5zpjxNq6Vpt4FdrTp9s6VFjSgQh5FzejwToj97i317dkxooSRIpQJHiPl2qQVGhBZhdSN1d7llgk51tQwQglASuABFm796kk4Zp6BLr2pQsSlRpRZBt6BSrCAZqSkCkjoPp4l7q5p6sCR6kk4ZrClHrRhAqmQCrDlIfngCszkJrmlDom5FdCAJcnoVoSBJbjRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&amp;msgID=I5975714342895652864_500&amp;markAsRead= Learn why we included this at the following link: https://www.linkedin.com/blink?simpleRedirect=0Ue3sQfmh9pmNzqnhOoipQsSlRpRZBt6BSrCAZqSkCr79lpmdFtD9BkT9BrmZQsTlzfm4CszkJrmlDom5FdCAJcnoVoSBJbjRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I5975714342895652864_500&markAsRead=
&copy; 2014, LinkedIn Corporation. 2029 Stierlin Ct. Mountain View, CA 94043, USA

**Comment by tinvaan** [comment]
:+1:
