### ISSUE TITLE
Wrong redirect at user links from table data in Article, GSoC

### ISSUE THREAD

**Issue by tonythomas01** [amfoss/club-website-2017#24]
Only profile links in Contributions table works perfectly. The change should be: 
http://foss.amrita.ac.in/register/pprahul/profile
should be changed to 
http://foss.amrita.ac.in/register/profile/pprahul/

so - probably https://github.com/amfoss/website/blob/master/templates/achievement/gsoc_view.html#L15 should be changed to : 
<a href="/register/profile/{{c.username.username}}" target="_blank">

**Comment by ash1794** [comment]
Issue seems fixed with the commit.
