### ISSUE TITLE
Phone Number and twitter showing wrong information

### ISSUE THREAD

**Issue by a0xnirudh** [amfoss/club-website-2017#3]
In the section **Connect with us** both phone number and twitter handle are wrong.

**Comment by tonythomas01** [comment]
fixed manually! almost broke the site though :\
file changed : fossWebsite/local_settings.py

**Comment by tonythomas01** [comment]
err. Wrong bug - that was for DEBUG flag

**Comment by tinajohnson** [comment]
Fixed ! Remove phone number and replaced with IRC
